version: '3'
services:
  redis:
    container_name: redis_requestbin
    image: redis
  requestbin:
    container_name: requestbin
    image: crccheck/requestbin
    # build: .
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      # SESSION_SECRET_KEY
      # BUGSNAG_KEY
    ports:
      - "1000:80"