version: '3.3'
services:
  db:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'Usuario_123'
      MYSQL_PASSWORD: 'Senha_123'
      MYSQL_ROOT_PASSWORD: 'root_123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /Users/srlopes/Programas/docker_volumes/mysql:/var/lib/mysql